class AddInitialIndexes < ActiveRecord::Migration
	def self.up
		add_index :campaigns, :enabled, :name => "enabled_index"
		add_index :ad_groups, :campaign_id, :name => "campaign_id_index"
		add_index :ads, :ad_group_id, :name => "ad_group_id_index"
		add_index :ads, :template_type_id, :name => "template_type_id_index"
		add_index :ads, :enabled, :name => "enabled_index"
		add_index :ads, [:template_type_id, :enabled], :name => "template_type_id_and_enabled_index"
		add_index :template_types, :name, :unique => true, :name => "name_index"
		add_index :templates, :type_id, :name => "type_id_index"
		add_index :publishers, :access_hash, :unique => true, :name => "access_hash_index"
		add_index :publishers, :enabled, :name => "enabled_index"
		add_index :publishers, [:access_hash, :enabled], :unique => true, :name => "access_hash_and_enabled_index"
		add_index :serving_stats, :publisher_id, :name => "publisher_id_index"
		add_index :serving_stats, :template_id, :name => "template_id_index"
		add_index :serving_stats, :ad_id, :name => "ad_id_index"
		add_index :serving_stats, :position, :name => "position_index"
		add_index :serving_stats, :time_served, :name => "time_served_index"
		add_index :serving_stats, :hash, :unique => true, :name => "hash_index"
		add_index :serving_stats, [:publisher_id, :template_id, :ad_id, :position, :time_served], :unique => true, :name => "lookup_index"
	end

	def self.down
		remove_index :campaigns, :name => "enabled_index"
		remove_index :ad_groups, :name => "campaign_id_index"
		remove_index :ads, :name => "ad_group_id_index"
		remove_index :ads, :name => "template_type_id_index"
		remove_index :ads, :name => "enabled_index"
		remove_index :ads, :name => "template_type_id_and_enabled_index"
		remove_index :template_types, :name => "name_index"
		remove_index :templates, :name => "type_id_index"
		remove_index :publishers, :name => "access_hash_index"
		remove_index :publishers, :name => "enabled_index"
		remove_index :publishers, :name => "access_hash_and_enabled_index"
		remove_index :serving_stats, :name => "publisher_id_index"
		remove_index :serving_stats, :name => "template_id_index"
		remove_index :serving_stats, :name => "ad_id_index"
		remove_index :serving_stats, :name => "position_index"
		remove_index :serving_stats, :name => "time_served_index"
		remove_index :serving_stats, :name => "hash_index"
		remove_index :serving_stats, :name => "lookup_index"
	end
end
